[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r requirements.txt --extra-index-url https://d33sy5i8bnduwe.cloudfront.net/simple/"]

[start]
cmd = "uvicorn server:app --host 0.0.0.0 --port ${PORT:-8001}"
